---
version: '3.9'
services:
  tomcat:
    image: tomcat:7.0
    ports:
      - "8080:8080"
    volumes:
      - data1:/usr/local/tomcat/webapps
      - data2:/usr/local/tomcat/ROOT
  maven:
    build: maven
    hostname: db
    volumes:
      - data1:/apps/webapps
      - data2:/apps/root
  db:
    image: mysql:5.5
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: FgbHy54seG
      MYSQL_DATABASE: baseapp
      MYSQL_USER: userapp
      MYSQL_PASSWORD: 7Sde4fGjz2
volumes:
  data1:
  data2:
  db_data: