---
version: '3.9'
services:
  tomcat:
    image: tomcat:7.0
    ports:
      - "8080:8080"
    volumes:
      - data1:/usr/local/tomcat/webapps
      - data2:/usr/local/tomcat/ROOT
  maven:
    build: maven
    volumes:
      - data1:/webapps
      - data2:/ROOT
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: FgbHy54seG
      MYSQL_DATABASE: base1
      MYSQL_USER: user1
      MYSQL_PASSWORD: 7Sde4fGjz2
volumes:
  data1:
  data2:
  db_data: